### ISSUE TITLE
RaspberryPI hardware config

### ISSUE THREAD

**Issue by bojanbass** [kryops/01v96-remote#12]
Hi there,

I wanted to connect my rPI with Yamaha 01v96, but don't know how to setup hardware connection between these two. The link in documentation appears to be dead:
http://www.siliconstuff.com/2012/08/serial-port-midi-on-raspberry-pi.html 

Thank you in advance, regards.
Bojan

**Comment by Shad-Rydalch** [comment]
Hello,

Please check https://github.com/Shad-Rydalch/01v96-remote/blob/master/raspberry/documentation.md <https://github.com/Shad-Rydalch/01v96-remote/blob/master/raspberry/documentation.md>

This fork of kryops’ 01v96 remote will work with USB.

Shad Rydalch

**Comment by kryops** [comment]
I found the page again: http://siliconstuff.blogspot.de/2012/08/serial-port-midi-on-raspberry-pi.html

I will update the documentation accordingly.

@Shad: When I have access to our 01v96 again I can see if I can merge in your fork, RPi USB support sounds awesome :)

Michael

**Comment by bojanbass** [comment]
Yes, USB support sound really great, will try that one first. Thank you both for the answers.

**Comment by bojanbass** [comment]
btw, @Shad-Rydalch, your package.json has a small error:

npm ERR! 404 Not Found: piUSB
npm ERR! 404 
npm ERR! 404 'piUSB' is not in the npm registry.

Looks like piUSB is not a package, it's only an argument for app startup.

Anyway, I will try to get this app running and hopefully contribute to this project later. Thank you for sharing this code.
