### ISSUE TITLE
Sync channel names, pairing over MIDI?

### ISSUE THREAD

**Issue by sman591** [kryops/01v96-remote#18]
First off, thanks for building this! I got it up an running almost immediately on a MacBook Pro + iPad setup.

I previously used a [01v96 MIX Control](http://www.greaterthan.us/gtc/store/Entries/2010/5/27_01v96_MIX_Control.html) app, paired with TouchOSC. This software also operated over the 01v96's MIDI protocol. One really useful feature it had was the ability to receive channel names.

Since this software presumably operates over the same MIDI protocol, there must be a way to also grab those channel names over MIDI? Rather than manually typing them in, as it works today.

I'll try to dig into this myself in the next hour; if I find anything I'll try to report back.

**Comment by kryops** [comment]
Hi @sman591 
yes that sounds like a pretty useful feature!
Unfortunately, I don't have access to a 01v96 device any more since I moved out of my parents' place, so I can't really continue development on this project with much confidence any more :-/
If you manage to get it working, you are most welcome to report your findings or open a PR :)

**Comment by sman591** [comment]
Ah, well I'm afraid we're both without reliable access to an 01v96 then 🙁 I usually only use this board once or twice a year-- but this was **fantastic** to use last night. 

I also didn't realize the channel names save between browsers, so I just ended up typing everything in on my laptop and it synced to my iPad.

That said, in case anyone stumbles upon this in the future, I did manage to capture some SysEx packets that correlate to channel names (via [MIDI Monitor](https://www.snoize.com/MIDIMonitor/)). 
* A 14-byte SysEx packet is sent back for each character in the 4-character channel names
* Numbering of the message continues from `00`, `01`, `02`, `03`, and repeats for each channel.

If anyone's interested in tackling it, you can get a dump of the packets captured by MIDI Monitor captured: https://www.dropbox.com/sh/9co8ae5ddqc95ur/AABQqsNZq3ZG3RjLJL0rAvtAa?dl=0

**Comment by kryops** [comment]
Hi @sman591 ,

it took me a few years, but I finally ended up implementing this feature for this project's successor [remote-mixer](https://github.com/kryops/remote-mixer) (though only the 16 character long names). It worked exactly as you described it, thanks for your research 😌 

If you still occasionaly use a 01v96, make sure to check it out 😉

**Comment by sman591** [comment]
That's awesome! I don't use the 01v as often anymore, but I'll definitely try remote-mixer out next time. If anything comes up I'll let you know
