### ISSUE TITLE
µWebSockets fails at NPM install (workaround)

### ISSUE THREAD

**Issue by sman591** [kryops/01v96-remote#19]
When I ran the initial `npm install` after cloning the repo, µWebSockets appeared to fail to install.

**Workaround:**
```bash
cd node_modules/uws
npm install
cd ../..
```

Source: https://github.com/facebook/react-native/issues/17410#issuecomment-383016009

**Comment by kryops** [comment]
Sounds like I should do a dependency upgrade, it's been a while :see_no_evil:

**Comment by kryops** [comment]
@sman591 I pushed an upgrade of all dependencies to their latest version. On my machine (Linux, Node v10.6.0) it installs fine now - could you confirm on your system?

**Comment by sman591** [comment]
Just tried reinstalling on both Node v8.11.3 LTS and v10.6.0 and both worked 👍
